name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -o bin/webpush-api-amd64-linux

    - name: Build Linux ARM
      run: GOOS=linux GOARCH=arm64 go build -o bin/webpush-api-arm64-linux

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o bin/webpush-api-amd64.exe

    - name: Build macOS
      run: GOOS=darwin GOARCH=amd64 go build -o bin/webpush-api-amd64-darwin

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webpush-api
        path: bin/

